- TrackForce/src/main/webapp/html/clientDetails.html
- TrackForce/src/main/webapp/js/mainApp.js
> charts update dynamically

- TrackForce/src/main/webapp/html/clientDetails.html
- TrackForce/src/main/webapp/js/mainApp.js
merge into client, adding legend to charts
> added series bars and chart legend

- TrackForce/src/main/webapp/js/mainApp.js
- TrackForce/src/test/java/com/revature/test/ClientPage.feature
- merging color changes with client branch
- updating clientPage.feature
> Ryan timms

- TrackForce/src/test/java/com/revature/services/DatabaseServicesTest.java
- TrackForce/src/test/java/testng.xml
configuring test xml and more unit tests
> configure testng xml and more unit tests

- TrackForce/src/main/webapp/html/home.html
- TrackForce/src/main/webapp/js/mainApp.js
first draft of home page charts
> home page charts

- TrackForce/src/main/java/com/revature/dao/AssociateDaoHibernate.java
- TrackForce/src/main/java/com/revature/dao/MarketingStatusDaoHibernate.java
- TrackForce/src/main/java/com/revature/model/AssociateInfo.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/java/com/revature/services/BatchesService.java
- TrackForce/src/test/java/com/revature/test/testAssociateDaoHibernate.java
- TrackForce/src/test/java/com/revature/test/testAssociateService.java
Associates were returning null values for marketing status and client which was causing errors with AssociateInfo. Has been fixed with this update.
> Associate null issue

- TrackForce/src/main/webapp/html/clientMapped.html
- TrackForce/src/main/webapp/html/skillset.html
- TrackForce/src/main/webapp/js/mainApp.js
Added chart changing buttons, and template for chart-click functions on clientMapped and skillset
> added change chart type buttons

- TrackForce/src/main/webapp/js/mainApp.js
> functioning clientMapped.html and skillset.html chart clicks

- TrackForce/src/main/java/com/revature/dao/DatabaseDAO.java
- TrackForce/src/main/java/com/revature/dao/DatabaseDAOImpl.java
- TrackForce/src/main/java/com/revature/services/DatabaseServices.java
- TrackForce/src/main/webapp/html/index.html
- TrackForce/src/main/webapp/js/databaseCtrl.js
Addition of 3rd button for static salesforce data, re-enabled delete button for graph refresh testing
> Database salesforce static

- TrackForce/src/main/java/com/revature/dao/DatabaseDAOImpl.java
- TrackForce/src/test/java/com/revature/dao/DatabaseDaoImplTest.java
also why are these tests disabled
> Revised Database DAO Impl tests, typo fix

- TrackForce/src/test/java/com/revature/dao/MarketingStatusDaoTest.java
- TrackForce/src/test/java/testng.xml
> Marketing Status DAO tests

- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/webapp/html/home.html
- TrackForce/src/main/webapp/js/databaseCtrl.js
> Database changes

- TrackForce/src/test/java/com/revature/dao/ClientDaoImplTest.java
fixed the clientdaoimpltest, stop copy pasting the code into the tests, that's not the point ;;
> fix clientdaoimpltest, add new test to it

- TrackForce/src/test/java/com/revature/dao/AssociateDaoImplTest.java
- TrackForce/src/test/java/com/revature/dao/ClientDaoImplTest.java
> added associatedaoimpl test

- TrackForce/src/test/java/com/revature/dao/AssociateDaoImplTest.java
> lol forgot one line

- TrackForce/src/test/java/com/revature/dao/UserDaoImplTest.java
> cleaned up userdaoimpl

- TrackForce/src/test/java/com/revature/dao/UserDaoImplTest.java
> fixed wonky data provider :(

- TrackForce/src/test/java/com/revature/dao/UserDaoImplTest.java
> removed the data provider that is no longer needed

- .gitignore
- TrackForce/src/main/java/com/revature/utils/DriverUtil.java
Changed the DriverUtil to not have hardcoded values for the driver paths.
> Driver util properties

- TrackForce/src/main/webapp/html/home.html
- TrackForce/src/main/webapp/js/databaseCtrl.js
changed reload into chain on response after populate / delete
> loading updates

- TrackForce/src/test/java/com/revature/services/AssociateServiceTest.java
> associate service unit tests

- TrackForce/src/test/java/com/revature/services/BatchesServiceTest.java
> BatchesServiceTest completed

- TrackForce/src/test/java/testng.xml
> modify testng.xml

- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/java/com/revature/services/BatchesService.java
Edited the BatchesService and AssociateService to be less smelly.
> Sonar services

- TrackForce/src/test/java/com/revature/services/HomeResourceTest.java
> add to homeresourcetest

- TrackForce/src/test/java/testng.xml
> added to testxml

- TrackForce/src/main/webapp/js/databaseCtrl.js
> deleteBD update

- NGTrackForce/src/app/app.module.ts
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.html
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.spec.ts
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.ts
Create files for the clientMapped component.
> Create clientMapped component files

- NGTrackForce/.gitignore
- TrackForce/.gitignore
intellij specific files added to .gitignores
> .gitignores updated to include intellij files

- NGTrackForce/karma.conf.js
- NGTrackForce/src/polyfills.ts
This is to enable testing for Jenkins
> updated karma config for headless browser support

- TrackForce/src/main/java/com/revature/services/BatchesService.java
- TrackForce/src/test/java/com/revature/services/BatchesServiceTest.java
fixed some tests, making sure valid time stamps are being provided
> Ticket null curriculum

- NGTrackForce/karma.conf.js
- NGTrackForce/package-lock.json
- NGTrackForce/package.json
- NGTrackForce/src/app/app.component.html
- NGTrackForce/src/app/app.component.spec.ts
- NGTrackForce/src/app/components/associate-list/associate-list.component.spec.ts
- NGTrackForce/src/app/components/client-list/client-list.component.spec.ts
- NGTrackForce/src/app/components/client-list/client-list.component.ts
- NGTrackForce/src/app/services/associates-service/associates-service.ts
Fixed dependency issues, added phantomjs launcher for headless browser testing
> fixed karma tests dependency issues

- NGTrackForce/src/app/components/batch-list/batch-list.component.ts
- NGTrackForce/src/app/services/batch-service/batch.service.ts
- NGTrackForce/src/environments/environment.ts
- TrackForce/src/main/java/com/revature/dao/BatchDaoHibernate.java
- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
- TrackForce/src/main/java/com/revature/entity/TfBatch.java
fixed environment url, more eager fetching
> Batch list convert2

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/associate-list/associate-list.component.ts
- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/services/associates-service/associates-service.ts
- TrackForce/src/main/java/com/revature/services/AssociateService.java
Fixed form component so that updating an associate works properly.
> fixed form page so update works

- NGTrackForce/src/app/components/batch-details/batch-details.component.css
- NGTrackForce/src/app/components/batch-details/batch-details.component.html
- NGTrackForce/src/app/components/batch-details/batch-details.component.ts
- NGTrackForce/src/app/components/batch-list/batch-list.component.html
- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/models/associate.model.ts
- NGTrackForce/src/app/routing/routes.ts
- NGTrackForce/src/app/services/batch-service/batch.service.ts
- TrackForce/src/main/java/com/revature/dao/BatchDao.java
- TrackForce/src/main/java/com/revature/dao/BatchDaoHibernate.java
- TrackForce/src/main/java/com/revature/model/AssociateInfo.java
- TrackForce/src/main/java/com/revature/model/BatchInfo.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/java/com/revature/services/BatchesService.java
- TrackForce/src/main/java/com/revature/services/UserResource.java
- TrackForce/src/main/resources/tests.properties
- TrackForce/src/test/java/com/revature/dao/BatchDaoImplTest.java
- TrackForce/src/test/java/com/revature/services/BatchesServiceTest.java
- TrackForce/src/test/java/com/revature/test/testBatchDaoHibernate.java
- TrackForce/src/test/java/com/revature/test/testBatchesService.java
fixed backend dto classes, namely batch to include and associate to include the batch id as well,
added/changed dao functions so that they search by batch id, instead of batch name; fixed dao, service tests accordingly
changed front end to pass batch id instead of name to backend
** todo: why is there no nav bar?
** todo: form-component update works only partially: doesn't update status, only updates client
> batch details works ok now; needs to be tested

- NGTrackForce/src/app/components/associate-list/associate-list.component.ts
- NGTrackForce/src/app/routing/routes.ts
Navigating to AssociateList component from skillset now filters associates based upon given parameters.
> Update associate frontend

- NGTrackForce/src/app/components/batch-list/batch-list.component.css
- NGTrackForce/src/app/components/batch-list/batch-list.component.html
> styling to conform to original app

- NGTrackForce/src/app/app.component.html
- NGTrackForce/src/app/app.module.ts
- NGTrackForce/src/app/components/create-user/create-user.component.html
- NGTrackForce/src/app/components/home/home.component.ts
- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/components/root/root.component.html
- NGTrackForce/src/environments/environment.prod.ts
- NGTrackForce/src/index.html
- NGTrackForce/src/styles.css
> Fix merge final

- README.md
> initial push

- TrackForce/src/main/java/com/revature/dao/InterviewDao.java
- TrackForce/src/main/java/com/revature/dao/InterviewDaoHibernate.java
- TrackForce/src/main/java/com/revature/entity/TfInterview.java
- TrackForce/src/main/java/com/revature/model/InterviewInfo.java
- TrackForce/src/main/java/com/revature/utils/Dao2DoMapper.java
Added interview columns to hibernate entities
> Interview bryan

- TrackForce/src/test/java/com/revature/test/services/BatchesServiceTest.java
> hotfix, error in service test.

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/associate-list/associate-list.component.ts
- NGTrackForce/src/app/components/associate-view/associate-view.component.html
Added drop-down lists  for filtering and updating Associates by verification status
> Added drop-down lists

- NGTrackForce/src/app/components/associate-list/associate-list.component.spec.ts
- NGTrackForce/src/app/components/batch-details/batch-details.component.spec.ts
- NGTrackForce/src/app/components/batch-list/batch-list.component.spec.ts
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.spec.ts
- NGTrackForce/src/app/components/create-user/create-user.component.spec.ts
- NGTrackForce/src/app/components/navbar/navbar.component.spec.ts
- NGTrackForce/src/app/services/client-service/client.service.spec.ts
- Removed a test for a function that no longer existed
- Fixed invalid creation of Authentication Service (Increased number of arguments)
-  Made another test test the right method (It was looking for it in the wrong place)
> Fixed compile errors

- TrackForce/pom.xml
- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
The jenkins build actually started failing on this when no changes were made to the code, but this was breaking the build, so I'm fixing it.
> Removed unused import causing build error. 

- NGTrackForce/src/app/constants/role.constants.ts
- NGTrackForce/src/app/constants/selected-status.constants.ts
- NGTrackForce/src/app/models/associate.model.ts
- NGTrackForce/src/app/models/batch.model.ts
- NGTrackForce/src/app/models/chart-scale.model.ts
- NGTrackForce/src/app/models/client.model.ts
- NGTrackForce/src/app/models/clientMapped.model.ts
- NGTrackForce/src/app/models/curriculum.model.ts
- NGTrackForce/src/app/models/end-client.model.ts
- NGTrackForce/src/app/models/interview.model.ts
- NGTrackForce/src/app/models/marketing-status.model.ts
- NGTrackForce/src/app/models/ng2-charts-options.model.ts
- NGTrackForce/src/app/models/placement.model.ts
- NGTrackForce/src/app/models/status-info.model.ts
- NGTrackForce/src/app/models/trainer.model.ts
- NGTrackForce/src/app/models/user.model.ts
Most deletions caused by auto-formatting.
> Add trainer model and updated other models. Formatted. 

- NGTrackForce/src/app/components/associate-list/associate-list.component.spec.ts
- NGTrackForce/src/app/components/associate-list/associate-list.component.ts
- NGTrackForce/src/app/components/batch-details/batch-details.component.spec.ts
- NGTrackForce/src/app/components/batch-details/batch-details.component.ts
- NGTrackForce/src/app/components/batch-list/batch-list.component.html
- NGTrackForce/src/app/components/batch-list/batch-list.component.spec.ts
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.html.orig
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.spec.ts
- NGTrackForce/src/app/components/create-user/create-user.component.spec.ts
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/components/navbar/navbar.component.spec.ts
- NGTrackForce/src/app/components/navbar/navbar.component.ts
- NGTrackForce/src/app/models/associate.model.ts
- NGTrackForce/src/app/models/client.model.ts
- NGTrackForce/src/app/models/interview.model.ts
- NGTrackForce/src/app/models/role.model.ts
- NGTrackForce/src/app/models/user.model.ts
Finished making the models work
> Angular model to java entity

- TrackForce/src/main/java/com/revature/application/Application.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/java/com/revature/services/BatchService.java
- TrackForce/src/main/java/com/revature/services/ClientService.java
- TrackForce/src/test/java/com/revature/test/admin/cukes/CreateUserCukes.java
- TrackForce/src/test/java/com/revature/test/admin/cukes/LoginCukes.java
- TrackForce/src/test/java/com/revature/test/admin/pom/CreateUserTab.java
- TrackForce/src/test/java/com/revature/test/admin/pom/Login.java
- TrackForce/src/test/java/com/revature/test/admin/testclasses/CreateUser.feature
- TrackForce/src/test/java/com/revature/test/admin/testclasses/HomeTab.feature
- TrackForce/src/test/java/com/revature/test/admin/testclasses/Login.feature
- TrackForce/src/test/java/com/revature/test/services/AssociateServiceTest.java
- TrackForce/src/test/java/com/revature/test/services/BatchesServiceTest.java
- TrackForce/src/test/java/com/revature/test/services/ClientServiceTest.java
- TrackForce/src/test/java/com/revature/test/utils/WaitToLoad.java
Changed the service mockito tests, cukes , features, poms and servicehooks class.
> completed updating service tests and cucumber features

- TrackForce/pom.xml
- TrackForce/src/main/java/com/revature/entity/TfUser.java
- TrackForce/src/main/resources/hibernate.cfg.xml
- TrackForce/src/main/resources/hibernate.properties
Added c3p0, should limit connections;
Note: still leaky connections occurring. Will need to wait to fix this. Anyone else can attempt to fix this, but keep in mind, it's a time dedication process.
> Merging server1804-2 into dev1804-2

- NGTrackForce/src/app/components/batch-list/batch-list.component.ts
- NGTrackForce/src/app/components/predictions/predictions.component.ts
- NGTrackForce/src/app/models/batch.model.ts
- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
- TrackForce/src/main/java/com/revature/daoimpl/InterviewDaoImpl.java
- TrackForce/src/main/java/com/revature/entity/TfInterview.java
- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
Added predictions functionality and fixed resources, DAO implementations for interviews
> Predictions

- NGTrackForce/src/app/app.component.css
- NGTrackForce/src/app/app.component.html
- NGTrackForce/src/app/components/associate-list/associate-list.component.css
- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/associate-view/associate-view.component.css
- NGTrackForce/src/app/components/associate-view/associate-view.component.html
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.css
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.html
- NGTrackForce/src/app/components/create-user/create-user.component.css
- NGTrackForce/src/app/components/create-user/create-user.component.html
- NGTrackForce/src/app/components/form-component/form.component.css
- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/home/home.component.css
- NGTrackForce/src/app/components/home/home.component.html
- NGTrackForce/src/app/components/home/home.component.spec.ts
- NGTrackForce/src/app/components/login/login.component.css
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.css
- NGTrackForce/src/app/components/predictions/predictions.component.css
- NGTrackForce/src/app/components/predictions/predictions.component.html
- NGTrackForce/src/app/components/predictions/predictions.component.spec.ts
- NGTrackForce/src/app/components/skillset/skillset.component.css
- NGTrackForce/src/app/components/skillset/skillset.component.html
> Fix footer merged into client1804-2

- TrackForce/src/main/java/com/revature/application/Application.java
- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
- TrackForce/src/main/java/com/revature/resources/UserResource.java
> Added default marketing status to create new associate.

- NGTrackForce/src/app/components/associate-view/associate-view.component.html
- NGTrackForce/src/app/components/batch-list/batch-list.component.ts
- NGTrackForce/src/app/components/predictions/predictions.component.ts
- NGTrackForce/src/app/components/trainer-view/trainer-view.component.ts
Added "start" and "end" to batch-list for binding purposes.
Updated associate view.html so that the batch name and endClient name are grabbed directly.
Added "start" and "end" to predictions for binding purposes.
Temporarily set succMsg and errMsg to booleans on trainer-view for compilation purposes.
> Fixed errors preventing a successful angular build.

- NGTrackForce/src/app/components/client-mapped/client-mapped.component.css
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.html
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.ts
- NGTrackForce/src/app/components/home/home.component.html
- NGTrackForce/src/app/components/skillset/skillset.component.html
- NGTrackForce/src/app/components/skillset/skillset.component.ts
still working on the other charts
> client mapped chart is fully functional

- NGTrackForce/src/app/components/associate-list/associate-list.component.spec.ts
- NGTrackForce/src/app/components/associate-view/associate-view.component.spec.ts
- NGTrackForce/src/app/components/login/login.component.spec.ts
- NGTrackForce/src/app/components/predictions/predictions.component.spec.ts
- NGTrackForce/src/app/components/skillset/skillset.component.spec.ts
- NGTrackForce/src/app/components/trainer-view/trainer-view.component.spec.ts
merging branch into dev 1804-2
> fixed some karma tests

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/services/associate-service/associate.service.ts
- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/test/java/com/revature/test/services/ClientServiceTest.java
Updated the associate form page and added approve assoc endpoint.
> Associate form

- NGTrackForce/src/app/components/create-user/create-user.component.ts
- TrackForce/src/test/java/com/revature/test/restAssured/AssociateResourceTest.java
We can create trainers and users normally again.
> Randombugs

- NGTrackForce/src/app/components/login/login.component.ts
- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
- TrackForce/src/main/java/com/revature/entity/TfBatch.java
- TrackForce/src/main/java/com/revature/entity/TfBatchLocation.java
- TrackForce/src/main/java/com/revature/entity/TfClient.java
- TrackForce/src/main/java/com/revature/entity/TfCurriculum.java
- TrackForce/src/main/java/com/revature/entity/TfEndClient.java
- TrackForce/src/main/java/com/revature/entity/TfInterview.java
- TrackForce/src/main/java/com/revature/entity/TfInterviewType.java
- TrackForce/src/main/java/com/revature/entity/TfMarketingStatus.java
- TrackForce/src/main/java/com/revature/entity/TfPlacement.java
- TrackForce/src/main/java/com/revature/entity/TfRole.java
- TrackForce/src/main/java/com/revature/entity/TfTrainer.java
- TrackForce/src/main/java/com/revature/entity/TfUser.java
- TrackForce/src/main/resources/ehcache.xml
- TrackForce/src/main/resources/hibernate.cfg.xml
Added a region to each bean and added a cache to solve the hundred of fault messages problem. 
Removed an extra query that was causing the login page for admins/sales/staging to be load super slow.
> Optimization

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/batch-list/batch-list.component.html
- NGTrackForce/src/app/components/client-list/client-list.component.html
- NGTrackForce/src/app/components/home/home.component.html
- NGTrackForce/src/app/components/login/login.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
> updating loading to test

- NGTrackForce/src/app/components/client-list/client-list.component.html
- NGTrackForce/src/app/components/client-list/client-list.component.ts
clicking "View Data for All Clients" now resets the search bar
> fixed #570

- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
Reverts revaturelabs/trackforce#590
> Revert "fixed tf associate"

- TrackForce/src/main/java/com/revature/dao/AssociateDao.java
- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
- TrackForce/src/main/java/com/revature/daoimpl/BatchDaoImpl.java
- TrackForce/src/main/java/com/revature/entity/TfBatch.java
- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/resources/hibernate.cfg.xml
Reverts revaturelabs/trackforce#586
> Revert "Optimization"

- NGTrackForce/src/app/components/batch-list/batch-list.component.html
- NGTrackForce/src/app/components/batch-list/batch-list.component.ts
- NGTrackForce/src/app/components/datetimepicker/datetimepicker.component.css
- NGTrackForce/src/app/components/datetimepicker/datetimepicker.component.spec.ts
- NGTrackForce/src/app/components/datetimepicker/datetimepicker.component.ts
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/main/java/com/revature/resources/UserResource.java
- TrackForce/src/main/java/com/revature/utils/HibernateUtil.java
- TrackForce/src/test/java/com/revature/test/restAssured/UserResourceTest.java
- TrackForce/src/test/java/com/revature/test/services/AssociateServiceTest.java
> Dev global fix

- NGTrackForce/src/app/components/associate-view/associate-view.component.spec.ts
- NGTrackForce/src/app/components/form-component/form.component.html
changed the (click) method to be the one that redirects to the interview-details page.
> changed form-component to redirect to the interview-details page

- NGTrackForce/src/app/components/associate-view/associate-view.component.html
- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
- TrackForce/src/main/java/com/revature/resources/UserResource.java
When creating a new interview, the default job description is no longer a random string of numbers.
> fixed default job description

- NGTrackForce/karma.conf.js
> fixed chromeheadless and singlerun true

- TrackForce/src/main/java/com/revature/resources/BatchResource.java
- TrackForce/src/main/java/com/revature/resources/UserResource.java
- TrackForce/src/test/java/com/revature/test/restAssured/UserResourceTest.java
bad credentials now returns a 200 status, but null for user data.
Tests corrected
Front end shows proper feedback
> Corrected bad login response

- NGTrackForce/src/app/components/login/login.component.ts
- TrackForce/src/main/java/com/revature/utils/HibernateUtil.java
Fixes #657
Change password requirement to user requirement
> Updated register error message

- TrackForce/src/main/java/com/revature/daoimpl/BatchDaoImpl.java
Added missing where clause to ensure the correct batch was being retrieved. Fixes issue #666
> BatchDaoImpl Fix

- TrackForce/src/main/java/com/revature/utils/HibernateUtil.java
Corrected layout to proper code conventions.
Optimized shutdown() with java 8 optimizations.
Cleaned up whitespace.
Fixes issue #723
> Updated Hibernate Util

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
- NGTrackForce/src/app/components/deployed/deployed.component.html
- NGTrackForce/src/app/components/form-component/form.component.html
> Associate with ID 0 is now loaded in associate list

- TrackForce/src/test/java/com/revature/test/admin/cuke/HomeTabCukes.java
- TrackForce/src/test/java/com/revature/test/admin/cuke/LoginCuke.java
- TrackForce/src/test/java/com/revature/test/admin/pom/HomeTab.java
- TrackForce/src/test/java/com/revature/test/runner/CucumberTestRunner.java
- TrackForce/src/test/java/com/revature/test/utils/ServiceHooks.java
- TrackForce/src/test/java/com/revature/test/utils/WebDriverUtil.java
- TrackForce/src/test/resources/AdminFeatureFiles/HomeTab.feature
tested the functionality of the links inside of the footer the using cucumber. This contributes to isssue #695
> More Cucumber Tests

- NGTrackForce/src/app/components/associate-list/associate-list.component.html
A merge conflict was brought in in the associate list html this resolves that.
> Fix for merge conflict that got pushed

- NGTrackForce/src/app/components/trainer-view/trainer-view.component.css
- NGTrackForce/src/app/components/trainer-view/trainer-view.component.html
- NGTrackForce/src/app/components/trainer-view/trainer-view.component.ts
- NGTrackForce/src/app/interceptors/invalidSessionReroute.interceptor.ts
- NGTrackForce/src/app/services/trainer-service/trainer.service.ts
- TrackForce/src/main/java/com/revature/resources/TrainerResource.java
Implemented trainer update on trainer-view component.  Added UI fixes.  Added HTTP put request.  Minor fix to TrainerResource.java where trainers were incorrectly being thrown a 401 error.
> Trainer update fix

- TrackForce/src/test/java/com/revature/test/services/UserServiceTest.java
Changed UserServiceTest so that it connects to database. Before, it was just checking the mock Mockito database.
> fixed UserService tests to actually touch database

- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/services/interview-service/interview.service.ts
> Added message to indicate approval success

- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
> Implemented associate paging resource

- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
removed redundant code and optimized native sql to criteriaquery.
> Added getCount optimization

- TrackForce/src/main/java/com/revature/utils/UserAuthentication.java
Made Jason fixes, sorry i am such a failure oh master JSON
> Authentication method

- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
changed to make fewer checks and be more efficient.
> Optimized count switch-AssociateDaoImpl

- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
Slight performance increase noticed on my end.
> Pagination update

- NGTrackForce/src/app/components/create-user/create-user.component.html
- NGTrackForce/src/app/components/create-user/create-user.component.ts
- NGTrackForce/src/app/components/create-user/create-user.enum.ts
- NGTrackForce/src/app/services/user-service/user.service.ts
- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
Implemented UI fixes to the Create User tab for an admin user.  Component will now display appropriate messages for invalid usernames, invalid or non-confirmed password, and will keep the button disabled until all appropriate information is put in, including the radio buttons.  Creating a user still throws a 417 error, but the front end portion of this component should be complete.
> Admin create user

- NGTrackForce/src/app/components/datetimepicker/datetimepicker.component.ts
- NGTrackForce/src/app/components/predictions/predictions.component.html
- NGTrackForce/src/app/components/predictions/predictions.component.ts
Set very simple range validation for year to be at least 2012
> Prediction tab year restriction

- TrackForce/src/test/java/com/revature/test/restAssured/TrainerResourceTest.java
Fixed changes in TrainerResourceTest using mock data provided from sql script. 100% passed.
> Fixed TrainerResourceTests to 100%

- NGTrackForce/chrome-test-report.html
- NGTrackForce/e2e/client-list/client-list-spec.ts
- NGTrackForce/e2e/client-list/client-list.po.ts
- NGTrackForce/protractor.conf.js
- NGTrackForce/testresults/xmloutput.xml
I check and added more test to test the functionality of the client list tab for admin, staging manager, and delivery/sales. Some test either fail or are skipped because of none bugs in the code. All together there are now 61 passing protractor test, 3 failing, and 6 skipped tests. This contributes to issue #699
> Protractor test for Client List tab for admin, staging manager, and delivery/sales

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
added tag "interviewType" for henry
> Interview Type tag

- TrackForce/src/test/java/com/revature/test/admin/cuke/AssociateViewCukes.java
- TrackForce/src/test/java/com/revature/test/admin/cuke/LoginCuke.java
- TrackForce/src/test/java/com/revature/test/admin/cuke/RegisterUserCuke.java
- TrackForce/src/test/java/com/revature/test/admin/pom/Login.java
- TrackForce/src/test/java/com/revature/test/runner/CucumberTestRunner.java
- TrackForce/src/test/resources/AdminFeatureFiles/Register.feature
- TrackForce/src/test/resources/tests.properties
Total Scenarios:35
Passing:34
Failing: 1
Total Steps: 280
Passing Steps: 279
Failing Steps: 1
Addresses issue #695
> Fixed Registration Cucumber Tests

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- NGTrackForce/src/app/services/interview-service/interview.service.ts
- TrackForce/src/test/java/com/revature/test/admin/cuke/AssociateViewCukes.java
- TrackForce/src/test/java/com/revature/test/admin/cuke/LoginCuke.java
- TrackForce/src/test/java/com/revature/test/admin/cuke/RegisterUserCuke.java
- TrackForce/src/test/java/com/revature/test/admin/pom/AssociateView.java
- TrackForce/src/test/java/com/revature/test/admin/pom/Login.java
- TrackForce/src/test/resources/AdminFeatureFiles/Register.feature
- TrackForce/src/test/resources/tests.properties
This commit contains 89 scenarios, 88 of which pass consistently.
The tests are rewritten to accomodate the most recent FrontEnd build,
with better branch coverage, boundary condition coverage, negative test
coverage, and less hardcoding.
All tests can now target any server via the test.properties file.
The failing scenario (confirm landing on associate page) is due to a
wait issue that I cannot consistently reproduce.
Addresses #695
> Cucumber Expanded For Most Recent FrontEnd

- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
Optimized getUndeployed method by merging redundant code and preserving method logic.
> AsssociateDaoImpl Optimize

- TrackForce/src/test/java/com/revature/test/restAssured/CurriculumResourceTest.java
Please look over, just changed lines that returned wrong responses because of bad token Id's
> Fixed one test in CurriculumResource now containing 100% passed

- NGTrackForce/chrome-test-report.html
- NGTrackForce/e2e/client-list/client-list.po.ts
- NGTrackForce/e2e/create-user/create-user.e2e-spec.ts
- NGTrackForce/e2e/create-user/create-user.po.ts
- NGTrackForce/e2e/login/login.po.ts
- NGTrackForce/e2e/navbar/navbar.po.ts
- NGTrackForce/protractor.conf.js
- NGTrackForce/testresults/xmloutput.xml
I added test to check the functionality of all feature, and error testing. I had to comment out all tests that create users other than trainer because of issues not allowing them to be registered. Finally I updated a few files that should allow the protractor test to be run on the pipeline. This contributes to issue #699
> Protractor create user tab

- NGTrackForce/src/app/components/deployed/deployed.component.html
Removing marker in the conflict causing fail builds.
> A merge conflict was pushed

- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/interview-details/interview-details.component.html
- NGTrackForce/src/app/components/interview-details/interview-details.component.ts
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
> Staging Manager interview functionality

- NGTrackForce/src/app/components/form-component/form.component.html
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/components/form-component/form.enum.ts
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- NGTrackForce/src/app/services/associate-service/associate.service.ts
Adds UI changes to the Admin's update associate page.  Provides for status messages that inform the user of whether the server's recieved a request or not.  Allows user to update an associate, however there is an issue on the back end where this update will nuke the associate's password.
> Update associate fix

- NGTrackForce/src/app/components/home/home.component.html
- NGTrackForce/src/app/models/ng2-charts-options.model.ts
Add bootstrap card
Move chart title to card header
Add border to seperate each card
> Homepage UI Update -2 

- NGTrackForce/src/app/components/batch-list/batch-list.component.html
- NGTrackForce/src/app/components/home/home.component.css
- NGTrackForce/src/app/components/home/home.component.html
- NGTrackForce/src/app/components/predictions/predictions.component.css
- NGTrackForce/src/app/components/predictions/predictions.component.html
Contains Home tab and Prediction Tab UI updates
> Prediction UI

- NGTrackForce/src/app/components/salesforce/salesforce.component.css
- NGTrackForce/src/app/components/salesforce/salesforce.component.html
These are UI changes to the salesforce page.
> New salesforce changes made 9/11

- NGTrackForce/src/app/components/navbar/navbar.component.html
New navbar changes made to merge.
> Navbar changes 9/11

- NGTrackForce/src/app/components/navbar/navbar.component.html
Reverts revaturelabs/trackforce#841
> Revert "Navbar changes 9/11"

- NGTrackForce/src/app/components/salesforce/salesforce.component.css
- NGTrackForce/src/app/components/salesforce/salesforce.component.html
> button fix

- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
> Authentication fixes to the Interview resource

- TrackForce/src/test/java/com/revature/pom/AdminNavbarElements.java
welcomeText was using an old xpath that is no longer valid.
> modified pom, welcomeText is now using id:

- TrackForce/src/main/java/com/revature/application/GenerateData.java
- TrackForce/src/test/java/com/revature/pom/AdminNavbarElements.java
- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
Fixed Generate.Data.getRandomData so it would not throw an exception, resulting in passing tests that relied on that method.
Updated AdminTests to reflect current client-side code.
> 1808 backend eagerlazyload

- TrackForce/src/main/java/com/revature/dao/AssociateDao.java
- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/test/java/com/revature/test/dao/AssociateDAOTest.java
- TrackForce/src/test/java/com/revature/test/services/AssociateServicesTest.java
Includes optimization of code responsible for database queries for the pie charts on the home page.
> 1808 backend art

- NGTrackForce/package.json
- NGTrackForce/src/app/components/trainer-view/trainer-view.component.ts
- TrackForce/src/main/java/com/revature/application/GenerateData.java
- TrackForce/src/main/java/com/revature/dao/AssociateDao.java
- TrackForce/src/main/java/com/revature/daoimpl/AssociateDaoImpl.java
- TrackForce/src/main/java/com/revature/entity/TfAssociate.java
- TrackForce/src/main/java/com/revature/entity/TfTrainer.java
- TrackForce/src/main/java/com/revature/entity/TfUser.java
- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/resources/BatchResource.java
- TrackForce/src/main/java/com/revature/resources/CurriculumResource.java
- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
- TrackForce/src/main/java/com/revature/resources/TrainerResource.java
- TrackForce/src/main/java/com/revature/resources/UserResource.java
- TrackForce/src/main/java/com/revature/services/AssociateService.java
- TrackForce/src/main/java/com/revature/services/JWTService.java
- TrackForce/src/main/java/com/revature/services/TrainerService.java
- TrackForce/src/main/java/com/revature/utils/ResourceHelper.java
- TrackForce/src/main/java/com/revature/utils/UserAuthentication.java
- TrackForce/src/test/java/com/revature/pom/AdminNavbarElements.java
- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
- TrackForce/src/test/java/com/revature/test/dao/AssociateDAOTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/UserResourceTest.java
- TrackForce/src/test/java/com/revature/test/services/AssociateServicesTest.java
- resources/Extra Materials/Trackforce_DB_full.sql
Completed merges between back-end sub teams and confirmed working application.
> For First Week Showcase

- TrackForce/src/test/java/com/revature/test/dao/AssociateDAOTest.java
documented test case 'testAssociateDAOCreateAssociate' and updated test case with updated database info so test case can pass
> updated test cases

- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/cuke/RegisterUserCuke.java
- TrackForce/src/test/java/com/revature/test/pom/Login.java
- TrackForce/src/test/resources/AdminFeatureFiles/Register.feature
Fixed Cucumber tests not waiting for elements to be loaded before looking for them. Removed unneeded System.outs.
> 1808 backend testng cory

- TrackForce/src/main/java/com/revature/entity/TfUser.java
- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateList.java
- TrackForce/src/test/java/com/revature/test/pom/CreateUser.java
- TrackForce/src/test/java/com/revature/test/pom/Login.java
- TrackForce/src/test/java/com/revature/test/services/UserServicesTest.java
I modified the AdminTests.java file in the TestNG package to work with the updated poms.  I also had to modify some of the poms to work with the test.
> 1808 unit dylan

- TrackForce/src/test/java/com/revature/test/orm/entity/TfAssociateTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfBatchLocationTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfBatchTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfClientTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfCurriculumTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfEndClientTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfInterviewTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfInterviewTypeTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfMarketingStatusTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfPlacementTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfRoleTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfTrainerTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfUserAndCreatorRolerContainerTest.java
- TrackForce/src/test/java/com/revature/test/orm/entity/TfUserTest.java
- TrackForce/src/test/java/com/revature/test/orm/util/HibernateUtilTest.java
- TrackForce/src/test/java/com/revature/test/orm/util/PasswordStorageTest.java
Renamed the folder that was called "junit" to "orm" and removed the little bit of junit that was still in the tests.
> Should be the last of the junit -Jacob

- NGTrackForce/src/app/guards/auth.guard.ts
- NGTrackForce/src/app/services/authentication-service/authentication.service.ts
Upon refresh, there was no call to get the user role again from the database, leaving it undefined. Simply added a call if getUserRole() returns undefined.
> Fixed refresh

- NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.html
- NGTrackForce/src/app/components/associate-list-page/update-dialog-component.html
- NGTrackForce/src/app/components/login/login.component.ts
Unique names have been given to all the ids. Will have to change x-paths in tests to match the new  ids.
> changed id names to be unique issue #893

- TrackForce/src/main/java/com/revature/utils/EnvManager.java
- TrackForce/src/test/java/com/revature/test/restAssured/AssociateResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/BatchResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/ClientResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/CurriculumResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/InterviewResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/TrainerResourceTest.java
- TrackForce/src/test/java/com/revature/test/restAssured/UserResourceTest.java
- TrackForce/src/test/java/com/revature/test/utils/WebDriverUtil.java
Signed-off-by: Mussab ElDash <mussab14@gmail.com>
@dvosecky  @PrososkiP @revcg  Would you please review
for issue #678
> removed hardcoded url and used envirnoment variable instead

- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/interceptors/invalidSessionReroute.interceptor.ts
- NGTrackForce/src/app/services/authentication-service/authentication.service.ts
- NGTrackForce/src/tsconfig.spec.json
- TrackForce/pom.xml
Added a 10 millisecond delay instead of calling login twice.
> changed hack to something useful issue #913

- TrackForce/src/test/java/com/revature/test/dao/InterviewDAOTest.java
- TrackForce/src/test/resources/testng.xml
Remove junit tests that no longer exist from testng.xml suite. Add
BeforeTest setup method in InterviewDAOTest to initialize interview
lists before each test to fix initialization issue.
> Fix testng.xml, fix InterviewDAOTest

- NGTrackForce/src/app/components/batch-details/batch-details.component.ts
- NGTrackForce/src/app/services/batch-service/batch.service.ts
This fixed the forever hang and simply outputs no associates found.
> checked to see if associates were null before accessing the length issue #863

- TrackForce/src/main/java/com/revature/entity/TfInterview.java
- TrackForce/src/main/resources/hibernate.cfg.xml
and in hibernate cfg added property line 9
> in TfIntervieW added admin at line 30 

- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/services/authentication-service/authentication.service.ts
Signed-off-by: Mussab ElDash <mussab14@gmail.com>
Issue #944 
If you got a slow connection the 10 milliseconds wait time isn't good enough so I changed the usage of the timeout function and used a callback function instead and now it doesn't matter if you have a slow connection or a fast one once you get the response back you'll be logged in
> Issue #944 replaced setTimeout with a callback function

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/main/java/com/revature/entity/TfInterview.java
- TrackForce/src/main/java/com/revature/resources/BatchResource.java
i fixed the interview button not adding the interview in the database which Renee had already done and i didnt know. But i also added the message dialog that shows for one second and disappears afterwards. Also the dynamic table now loads in the bottom as well.
> add interview works, success message also works with timeout

- TrackForce/src/test/java/com/revature/test/cuke/AssociateViewCukes.java
- TrackForce/src/test/java/com/revature/test/cuke/LoginCuke.java
- TrackForce/src/test/java/com/revature/test/utils/TestConfig.java
Changed gluecode (cukes) and TestConfig.java to incorporate EnvManager.java instead of the hard-coded url in test.properties.
> Changed TestConfig.java to incorporate EnvManager.java issue810

- NGTrackForce/chrome-test-report.html
- NGTrackForce/e2e/app/app.po.ts
- NGTrackForce/e2e/associate-list/associate-list-client.js
- NGTrackForce/e2e/associate-list/associate-list-curriculum.js
- NGTrackForce/e2e/associate-list/associate-list-pagenation.js
- NGTrackForce/e2e/associate-list/associate-list-search.js
- NGTrackForce/e2e/associate-list/associate-list-status.js
- NGTrackForce/protractor.conf.js
- NGTrackForce/testresults/xmloutput.xml
Fixed 3 of the associate list tests so that they could be uncommented on protractor.conf.js
> Issue705 test

- TrackForce/src/main/java/com/revature/daoimpl/UserDaoImpl.java
- TrackForce/src/test/java/com/revature/test/dao/ClientDAOTest.java
- TrackForce/src/test/java/com/revature/test/dao/InterviewDAOTest.java
- TrackForce/src/test/java/com/revature/test/dao/MarketingStatusDAOTest.java
- TrackForce/src/test/java/com/revature/test/dao/TrainerDAOTest.java
- TrackForce/src/test/java/com/revature/test/dao/UserDAOTest.java
Commented heavily the LoginCuke test file with reconfiguration recommendations, observations, and notes. Implemented a configuration method for the WebDriver for the utils webDriver.
> Issue697 tests

- NGTrackForce/src/app/services/associate-service/associate.service.ts
- NGTrackForce/src/app/services/trainer-service/trainer.service.ts
- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/test/java/com/revature/test/restAssured/AssociateResourceTest.java
> fixed issue: Duplicate paths in AssociateResources.java #980

- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
> Commit changes made to AdminTests.java

- NGTrackForce/src/app/services/client-service/client.service.ts
> fixed client services in Angular. Lists properly now.

- NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.ts
- NGTrackForce/src/app/components/batch-details/batch-details.component.ts
- NGTrackForce/src/app/components/batch-list/batch-list.component.ts
- NGTrackForce/src/app/components/client-list/client-list.component.ts
- NGTrackForce/src/app/components/client-mapped/client-mapped.component.ts
- NGTrackForce/src/app/components/deployed/deployed.component.ts
- NGTrackForce/src/app/components/form-component/form.component.ts
- NGTrackForce/src/app/components/home/home.component.ts
- NGTrackForce/src/app/components/interview-details/interview-details.component.ts
- NGTrackForce/src/app/components/interviews-view/interviews-view.component.ts
- NGTrackForce/src/app/components/invalid-session/invalid-session.component.ts
- NGTrackForce/src/app/components/login/login.component.ts
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- NGTrackForce/src/app/components/predictions/predictions.component.ts
- NGTrackForce/src/app/components/skillset/skillset.component.spec.ts
- NGTrackForce/src/app/components/skillset/skillset.component.ts
- NGTrackForce/src/app/components/undeployed/undeployed.component.ts
- NGTrackForce/src/app/services/authentication-service/authentication.service.ts
- NGTrackForce/src/app/services/batch-service/batch.service.spec.ts
- NGTrackForce/src/app/services/curriculum-service/curriculum-service.spec.ts
- NGTrackForce/src/app/services/datasync-service/data-sync.service.ts
Updates primarily to error logging to help track down issues
> Part 2 of #698 Fix Jasmine Test, stil work in progress

- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
Fixed some of the failed test in AdminTestNG. Now there are only 1 fail and 2 skips.
> fixed failed test

- NGTrackForce/src/app/components/batch-list/batch-list.component.css
- TrackForce/src/main/java/com/revature/resources/ClientResource.java
Update to use -1 for client id in resource
> Issue #1016: Fix for view all client on batch list, #1018 Fixing batch list scrollbar

- TrackForce/src/main/java/com/revature/resources/ClientResource.java
Fix for associates not being able to schedule interviews, client list permissions
> #722 Fix for associate not adding/updating interviews

- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
> still editing admintest

- TrackForce/src/main/java/com/revature/resources/AssociateResource.java
- TrackForce/src/main/java/com/revature/resources/BatchResource.java
- TrackForce/src/main/java/com/revature/resources/ClientResource.java
First set of loggers for Resources in Java.
> First batch of loggers

- TrackForce/src/main/java/com/revature/resources/CurriculumResource.java
- TrackForce/src/main/java/com/revature/resources/InitResource.java
- TrackForce/src/main/java/com/revature/resources/InterviewResource.java
- TrackForce/src/main/java/com/revature/resources/TrainerResource.java
- TrackForce/src/main/java/com/revature/resources/UserResource.java
Second/Final batch of loggers for Resource End-points.
> Final batch of loggers for com.revature.resources

- NGTrackForce/src/app/components/predictions/predictions.component.html
- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
added some id in prediction.html for locating elements so that I can grab them in AdminTest.java
> added test method

- TrackForce/src/test/java/com/revature/test/cuke/LoginCuke.java
- TrackForce/src/test/resources/AdminFeatureFiles/LoginFirefox.feature
Completed Login on Firefox testing
> Fully implemented and passed Firefox testing

- NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.ts
- NGTrackForce/src/app/components/associate-list-page/update-dialog-component.html
- TrackForce/src/main/java/com/revature/services/TrainerService.java
- TrackForce/src/test/java/com/revature/test/services/TrainerServicesTest.java
Angular: No longer default setting first client in list if no option selected.
Fixed some service tests. Still need to revisit at some, but got working for now.
> Updated some ServiceTests and 1 angular issue

- TrackForce/src/main/java/com/revature/services/UserService.java
- TrackForce/src/test/java/com/revature/test/services/UserServicesTest.java
UserServiceTests are functional.
> made the userServiceTests functional

- NGTrackForce/src/app/components/usernameupdate/usernameupdate.component.spec.ts
> Fix for usernameupdate spec references

- NGTrackForce/src/app/components/create-user/create-user.component.spec.ts
- NGTrackForce/src/app/components/passwordupdate/passwordupdate.component.spec.ts
- NGTrackForce/src/app/components/passwordupdate/passwordupdate.component.ts
- NGTrackForce/src/app/components/usernameupdate/usernameupdate.component.spec.ts
- NGTrackForce/src/app/components/usernameupdate/usernameupdate.component.ts
These tests currently fail because the component's user object's id is currently null.
> Updated UpdateUsername Component Test Suite

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/test/java/com/revature/test/cuke/AssociateViewCukes.java
- TrackForce/src/test/java/com/revature/test/cuke/ConstantsCukeTestUtil.java
- TrackForce/src/test/java/com/revature/test/pom/NavBar.java
- TrackForce/src/test/java/com/revature/test/pom/PasswordUpdate.java
- TrackForce/src/test/java/com/revature/test/pom/UsernameUpdate.java
- TrackForce/src/test/resources/AdminFeatureFiles/AssociateView.feature
Username and Password Associate tests now pull the proper update screen from the navbar. 
Also, they exist.
> Modified and added Cuke tests for username/password update

- NGTrackForce/src/app/components/associate-view/associate-view.component.html
- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateHome.java
Added a test method to automate changing associate info
> test for updating Associate First and Last name

- TrackForce/src/test/java/com/revature/test/resources/AssociateResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/BatchResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/ClientResource.java
- TrackForce/src/test/java/com/revature/test/resources/CurriculumResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/InitResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/InterviewResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/TrainerResourceTest.java
- TrackForce/src/test/java/com/revature/test/resources/UserResourceTest.java
tests the same things as restAssured, but at a unit level
> Created Resource.Test package for unit tests of resources

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateHome.java
I have added some identifiers to make testing interview  page easier for me
> added identifiers to test adding an interview

- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateHome.java
Added an interview test for Associate
> added an interview for Associate test

- NGTrackForce/chrome-test-report.html
- NGTrackForce/e2e/configuration/test-config.ts
- NGTrackForce/e2e/create-user/create-user.e2e-spec.ts
- NGTrackForce/e2e/register-associate/register-associate.e2e-spec.ts
- NGTrackForce/protractor.conf.js
- NGTrackForce/testresults/xmloutput.xml
> fixed a few protractor tests

- TrackForce/src/test/java/com/revature/test/TestNG/AdminTests.java
- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateHome.java
added wait time for debugging. the test is passing is debugging, but failed on normal run
> added wait time

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
> date format change

- NGTrackForce/chrome-test-report.html
- NGTrackForce/e2e/create-user/create-user.e2e-spec.ts
- NGTrackForce/e2e/login/login.e2e-spec.ts
- NGTrackForce/testresults/xmloutput.xml
> cleaned up some protractor code. added some waits.

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/test/java/com/revature/test/TestNG/AssociateTests.java
- TrackForce/src/test/java/com/revature/test/pom/AssociateHome.java
used tabs to fix the year field
> using tab to fix the year field

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
The minimum date to select an interview is today's date. Also, removed redundant syntax in the date regex.
> Made minimum date to today

- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
- NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
- TrackForce/src/test/java/com/revature/test/cuke/AssociateViewCukes.java
- TrackForce/src/test/java/com/revature/test/cuke/ConstantsCukeTestUtil.java
- TrackForce/src/test/java/com/revature/test/pom/MyInterviews.java
- TrackForce/src/test/resources/AdminFeatureFiles/AssociateView.feature
Fixed flaky tests and finished step implementations for updating an interview. Added some waits to fix many of the flaky tests.
> fixed flaky tests and added more tests

- TrackForce/src/main/java/com/revature/dao/InterviewDao.java
- TrackForce/src/main/java/com/revature/daoimpl/InterviewDaoImpl.java
Changed data type from int to Integer in getInterviewById method because id is supposed to be an Integer in the TfInterview class.
> changed data type in getInterviewById method

- TrackForce/pom.xml
- TrackForce/src/test/java/com/revature/test/runner/CucumberTestRunner.java
Reverts revaturelabs/trackforce#1202
> Revert "added dependency and code to generate cucumber test results"
